name: História de usuário
description: Nova história para o backlog
labels: ["história"]
body:
  - type: input
    id: como
    attributes:
      label: Como (perfil de usuário)
      placeholder: "leitor"
    validations:
      required: true
  - type: input
    id: quero
    attributes:
      label: Quero (ação)
      placeholder: "renovar meu empréstimo pela internet"
    validations:
      required: true
  - type: input
    id: para
    attributes:
      label: Para (benefício)
      placeholder: "não precisar ir até a biblioteca"
    validations:
      required: true
  - type: textarea
    id: regras
    attributes:
      label: Regras de negócio relacionadas
      placeholder: "RN04, RN06"
  - type: textarea
    id: criterios
    attributes:
      label: Critérios de aceite (Dado / Quando / Então)
      value: |
        - Dado que ..., quando ..., então ...
        - Dado que ..., quando ..., então ...
    validations:
      required: true
  - type: textarea
    id: tarefas
    attributes:
      label: Tarefas
      value: |
        - [ ]
